# Sesión 2 - Práctica 2: Colas de Prioridad y Clases
## Estructuras Avanzadas para Algoritmos de Búsqueda

**Técnicas de Sistemas Inteligentes - 2025/2026**

---

### Objetivos:
- Entender y usar colas de prioridad con `heapq`
- Crear clases para representar nodos de búsqueda
- Trabajar con NumPy para operaciones numéricas

### VERSIÓN PARA CLASE EN VIVO
Algunas partes están incompletas - las completaremos juntos

## 1. Colas de Prioridad con heapq

En A*, necesitamos siempre elegir el nodo con menor f(n) = g(n) + h(n).

In [3]:
import heapq

# Crear cola de prioridad
pq = []

# Añadir elementos: (prioridad, dato)
heapq.heappush(pq, (5, 'tarea C'))
heapq.heappush(pq, (1, 'tarea A'))  # Menor = más urgente
heapq.heappush(pq, (3, 'tarea B'))
heapq.heappush(pq, (10, 'tarea D'))

print("Extrayendo por prioridad:")
while pq:
    prioridad, tarea = heapq.heappop(pq)
    print(f"  {tarea} (prioridad={prioridad})")

Extrayendo por prioridad:
  tarea A (prioridad=1)
  tarea B (prioridad=3)
  tarea C (prioridad=5)
  tarea D (prioridad=10)


In [4]:
# Ejemplo con A*: Nodos con f(n)
import heapq

frontera = []

# Formato: (f_n, g_n, nodo)
heapq.heappush(frontera, (10, 0, 'A'))  # f=10
heapq.heappush(frontera, (12, 5, 'B'))  # f=12
heapq.heappush(frontera, (9, 3, 'C'))   # f=9  ← este será elegido

# Extraer nodo con menor f(n)
f_n, g_n, nodo = heapq.heappop(frontera)
print(f"Nodo elegido: {nodo} con f(n)={f_n}, g(n)={g_n}")

Nodo elegido: C con f(n)=9, g(n)=3


## 2. EJERCICIO EN VIVO: Clase para Nodos de Búsqueda

Vamos a crear juntos una clase `SearchNode` para A*.

In [5]:
import heapq
import itertools

class SearchNode:
    """Nodo para A* con f(n) = g(n) + h(n)."""
    
    def __init__(self, state, parent=None, action=None, path_cost=0, heuristic=0):
        """Inicializar nodo.
        
        Args:
            state: Estado del mundo
            parent: Nodo padre
            action: Acción que llevó aquí
            path_cost: g(n) - costo desde inicio
            heuristic: h(n) - estimación hasta objetivo
        """
        # TODO: Completar inicialización
        self.state = state
        self.parent = parent
        self.action = action
        self.path_cost = path_cost
        self.heuristic = heuristic
        self.f_score = path_cost + heuristic
    
    def __lt__(self, other):
        """Comparar nodos por f(n) para heapq."""
        return self.f_score < other.f_score
    
    def __repr__(self):
        return f"<Node {self.state} f={self.f_score:.1f}>"

# Probar la clase
nodo_a = SearchNode(state='A', path_cost=0, heuristic=10)
nodo_b = SearchNode(state='B', path_cost=5, heuristic=7)

print(nodo_a)
print(nodo_b)
print(f"\n¿B tiene menor f(n) que A? {nodo_b < nodo_a}")

<Node A f=10.0>
<Node B f=12.0>

¿B tiene menor f(n) que A? False


In [6]:
# Probar con heapq
frontera = []
contador = itertools.count()

nodo_a = SearchNode(state='A', path_cost=0, heuristic=10)
nodo_b = SearchNode(state='B', path_cost=5, heuristic=7)
nodo_c = SearchNode(state='C', path_cost=3, heuristic=6)

heapq.heappush(frontera, (nodo_a.f_score, next(contador), nodo_a))
heapq.heappush(frontera, (nodo_b.f_score, next(contador), nodo_b))
heapq.heappush(frontera, (nodo_c.f_score, next(contador), nodo_c))

print("Orden de exploración (por f(n)):")
while frontera:
    _, _, nodo = heapq.heappop(frontera)
    print(f"  {nodo.state}: g={nodo.path_cost}, h={nodo.heuristic}, f={nodo.f_score}")

Orden de exploración (por f(n)):
  C: g=3, h=6, f=9
  A: g=0, h=10, f=10
  B: g=5, h=7, f=12


## 3. NumPy para Operaciones Numéricas

In [7]:
import numpy as np

# Crear grid 5x5
grid = np.zeros((5, 5), dtype=int)

# Marcar obstáculos (1)
grid[1, 1] = 1
grid[2, 2] = 1
grid[3, 1] = 1

# Marcar inicio (2) y objetivo (3)
grid[0, 0] = 2
grid[4, 4] = 3

print("Grid:")
print(grid)
print("\nLeyenda: 0=libre, 1=obstáculo, 2=inicio, 3=objetivo")

Grid:
[[2 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 1 0 0 0]
 [0 0 0 0 3]]

Leyenda: 0=libre, 1=obstáculo, 2=inicio, 3=objetivo


In [ ]:
# Distancias
import numpy as np

p1 = np.array([0, 0])
p2 = np.array([3, 4])

# Distancia euclidiana
dist_euclidiana = np.linalg.norm(p2 - p1)
print(f"Distancia euclidiana: {dist_euclidiana}")

# Distancia Manhattan (para grids)
dist_manhattan = np.sum(np.abs(p2 - p1))
print(f"Distancia Manhattan: {dist_manhattan}")

## 4. EJERCICIO EN VIVO: Heurística Manhattan para 8-puzzle

Vamos a implementar juntos la heurística de distancia Manhattan.

In [9]:
import numpy as np

def manhattan_distance_puzzle(state, goal):
    """
    Calcula distancia Manhattan para 8-puzzle.
    
    Args:
        state: Array 3x3 con estado actual
        goal: Array 3x3 con estado objetivo
    
    Returns:
        Suma de distancias Manhattan de cada pieza
    """
    # TODO: Implementar heurística Manhattan
    # Pistas:
    # 1. Para cada número del 1 al 8:
    #    - Encontrar su posición en state: np.argwhere(state == num)[0]
    #    - Encontrar su posición en goal: np.argwhere(goal == num)[0]
    #    - Calcular distancia Manhattan: suma de valores absolutos de diferencias
    # 2. Sumar todas las distancias
    
    distance = 0
    
    for num in range(1, 9):  # Para cada número 1-8
        # COMPLETAR: encontrar posición actual
        current_pos = np.argwhere(state == num)[0]
        
        # COMPLETAR: encontrar posición objetivo
        goal_pos = np.argwhere(goal == num)[0]
        
        # COMPLETAR: sumar distancia Manhattan
        distance += np.sum(np.abs(current_pos - goal_pos))
    
    return distance

def misplaced_tiles(state, goal):
    """Cuenta fichas fuera de lugar (heurística más simple)."""
    return np.sum((state != goal) & (state != 0))

# Probar
state = np.array([
    [1, 2, 3],
    [4, 0, 5],
    [6, 7, 8]
])

goal = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 0]
])

print("Estado:")
print(state)
print("\nObjetivo:")
print(goal)
print()

h1 = misplaced_tiles(state, goal)
h2 = manhattan_distance_puzzle(state, goal)

print(f"h1 (misplaced tiles): {h1}")
print(f"h2 (Manhattan distance): {h2}")
print(f"\n¿Manhattan es más informativa? {h2} >= {h1}")

Estado:
[[1 2 3]
 [4 0 5]
 [6 7 8]]

Objetivo:
[[1 2 3]
 [4 5 6]
 [7 8 0]]

h1 (misplaced tiles): 4
h2 (Manhattan distance): 6

¿Manhattan es más informativa? 6 >= 4


## 5. Ejercicio Integrador

Simulación simple de los componentes de A*.

In [ ]:
import heapq
import numpy as np
import itertools

class AStarNode:
    """Nodo para simulación de A*."""
    
    def __init__(self, position, goal, parent=None, g_cost=0):
        self.position = position  # (x, y)
        self.parent = parent
        self.g_cost = g_cost
        
        # Calcular heurística (Manhattan)
        self.h_cost = abs(position[0] - goal[0]) + abs(position[1] - goal[1])
        self.f_cost = g_cost + self.h_cost
    
    def __lt__(self, other):
        return self.f_cost < other.f_cost
    
    def __repr__(self):
        return f"<Node {self.position} f={self.f_cost}>"

# Simulación
inicio = (0, 0)
objetivo = (4, 4)

frontera = []
contador = itertools.count()

# Nodo inicial
nodo_inicio = AStarNode(inicio, objetivo, g_cost=0)
heapq.heappush(frontera, (nodo_inicio.f_cost, next(contador), nodo_inicio))

print(f"Nodo inicial: {nodo_inicio.position}")
print(f"  g={nodo_inicio.g_cost}, h={nodo_inicio.h_cost}, f={nodo_inicio.f_cost}")
print()

# Expandir vecinos
vecinos = [(1, 0), (0, 1)]  # derecha, abajo

for dx, dy in vecinos:
    nueva_pos = (nodo_inicio.position[0] + dx, nodo_inicio.position[1] + dy)
    nuevo_nodo = AStarNode(nueva_pos, objetivo, parent=nodo_inicio, g_cost=1)
    heapq.heappush(frontera, (nuevo_nodo.f_cost, next(contador), nuevo_nodo))
    
    print(f"Vecino: {nueva_pos}")
    print(f"  g={nuevo_nodo.g_cost}, h={nuevo_nodo.h_cost}, f={nuevo_nodo.f_cost}")
    print()

# Extraer siguiente
_, _, siguiente = heapq.heappop(frontera)
print(f"Siguiente nodo a explorar: {siguiente.position} (f={siguiente.f_cost})")

## Resumen

Hoy hemos aprendido:

1. **heapq** para colas de prioridad
2. **Clases para nodos** con f(n) = g(n) + h(n)
3. **NumPy** para distancias y heurísticas

**Próximo notebook:** Primera clase Agent y GridWorld